import requests
from bs4 import BeautifulSoup
import json

# 크롤링하고자 하는 URL 목록
urls = [
    "https://www.syu.ac.kr/about-sahmyook/history-vision/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/vision/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/educational-objectives/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/founding-ideas/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/100th-anniversary/",
    "https://www.syu.ac.kr/about-sahmyook/symbols-ui/",
    "https://www.syu.ac.kr/about-sahmyook/symbols-ui/motto/",
    "https://www.syu.ac.kr/about-sahmyook/symbols-ui/logo-ui/",
    "https://www.syu.ac.kr/about-sahmyook/symbols-ui/school-song/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/faculty/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/phone-number/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/campus-map/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/directions/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/campus-tour-application/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/family-site/",
    "https://www.syu.ac.kr/about-sahmyook/organization/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/news-of-the-president/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/press/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/speeches/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/sinmungo3/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/former-president/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/information-disclosure-request/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/information-disclosure/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/budget-announcement/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/settlement-announcement/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/tuition-review-committee/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/panel-notice/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/self-assessment-report/",
    "https://www.syu.ac.kr/admissions-education/",
    "https://www.syu.ac.kr/admissions-education/admission-information/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/educational-guide/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/major-education-guide/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/uncultured-education/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/mvp-certificate-2013/",
    "https://www.syu.ac.kr/admissions-education/college/",
    "https://www.syu.ac.kr/admissions-education/college/theological-college/",
    "https://www.syu.ac.kr/admissions-education/college/creativity-and-convergence/",
    "https://www.syu.ac.kr/admissions-education/college/a-college-of-pharmacy/",
    "https://www.syu.ac.kr/admissions-education/college/smith-college-of-arts/",
    "https://www.syu.ac.kr/admissions-education/graduate-school/",
    "https://www.syu.ac.kr/industry-academic-research/",
    "https://www.syu.ac.kr/industry-academic-research/industry-academic-consortium/",
    "https://www.syu.ac.kr/health-science-feature-project/",
    "https://www.syu.ac.kr/industry-academic-research/su-edumi/",
    "https://www.syu.ac.kr/industry-academic-research/su-agri/",
    "https://www.syu.ac.kr/industry-academic-research/research-aid-project/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/",
    "https://www.syu.ac.kr/common-device-laboratory/",
    "https://www.syu.ac.kr/academic/",
    "https://www.syu.ac.kr/academic/major-schedule/",
    "https://www.syu.ac.kr/academic/faq/",
    "https://www.syu.ac.kr/academic/academic-info/",
    "https://www.syu.ac.kr/academic/academic-info/course-guide/",
    "https://www.syu.ac.kr/academic/academic-info/major-system/",
    "https://www.syu.ac.kr/academic/academic-info/academic-fluctuations/",
    "https://www.syu.ac.kr/academic/academic-info/class-guidance/",
    "https://www.syu.ac.kr/academic/academic-info/application-for-classes/",
    "https://www.syu.ac.kr/academic/academic-info/graduation/",
    "https://www.syu.ac.kr/academic/academic-info/credit-recognition/",
    "https://www.syu.ac.kr/academic/academic-info/seasonal-semester/",
    "https://www.syu.ac.kr/academic/academic-info/online-lecture/",
    "https://www.syu.ac.kr/academic/academic-info/change-personal-information/",
    "https://www.syu.ac.kr/academic/academic-info/college-cradle/",
    "https://www.syu.ac.kr/academic/academic-info/academic-contact-information/",
    "https://www.syu.ac.kr/school-life/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/",
    "https://www.syu.ac.kr/school-life/facility-information/",
    "https://www.syu.ac.kr/school-life/certificate/",
    "https://www.syu.ac.kr/school-life/life-counseling/",
    "https://www.syu.ac.kr/school-life/dormitory/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/",
    "https://www.syu.ac.kr/school-life/circles/",
    "https://www.syu.ac.kr/school-life/school-bus/",
    "https://www.syu.ac.kr/school-life/parking/",
    "https://www.syu.ac.kr/school-life/ad-publishing/",
    "https://www.syu.ac.kr/school-life/military-information/",
    "https://www.syu.ac.kr/school-life/venue-rental-info/",
    "https://www.syu.ac.kr/school-life/accommodation-guide/",
    "https://www.syu.ac.kr/university-square/",
    "https://www.syu.ac.kr/academic/academic-notice/",
    "https://www.syu.ac.kr/university-square/notice/event/",
    "https://www.syu.ac.kr/university-square/notice/campus-notice/",
    "https://www.syu.ac.kr/news-center/",
    "https://www.syu.ac.kr/university-square/syu-news/syu-news/",
    "https://www.syu.ac.kr/university-square/syu-news/planning/",
    "https://www.syu.ac.kr/university-square/syu-news/press-release/",
    "https://www.syu.ac.kr/university-square/promotion/newsletter/",
    "https://www.syu.ac.kr/scholarship-loan-notice/",
    "https://www.syu.ac.kr/academic/scholarship-information/scholarship-notice/",
    "https://www.syu.ac.kr/university-square/notice/employment-founding-announcement/",
    "https://www.syu.ac.kr/university-square/notice/job-offer/",
    "https://www.syu.ac.kr/university-square/notice/external-notice/",
    "https://www.syu.ac.kr/etc/bid-notice/",
    "https://www.syu.ac.kr/university-square/notice/recruitment/",
    "https://www.syu.ac.kr/syu-board-usage-guide/",
    "https://www.syu.ac.kr/sahmyook/",
    "https://www.syu.ac.kr/sahmyook/sahmtook-foundation/",
    "https://www.syu.ac.kr/sahmyook/about-sahmyook-foundation/",
    "https://www.syu.ac.kr/sahmyook/member-introduction/",
    "https://www.syu.ac.kr/sahmyook/corporation-info/",
    "https://www.syu.ac.kr/sahmyook/corporate-organization-info/",
    "https://www.syu.ac.kr/sahmyook/corporation-minutes/",
    "https://www.syu.ac.kr/sahmyook/corporate-constitution/",
    "https://www.syu.ac.kr/privacy-policy-before-20200401/",
    "https://www.syu.ac.kr/sahmyook/university-information-disclosure/",
    "https://www.syu.ac.kr/sahmyook/university-information-disclosure-2/",
    "https://www.syu.ac.kr/etc/site-map/",
    "https://www.syu.ac.kr/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history-main/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/major-education-guide2/",
    "https://www.syu.ac.kr/etc/",
    "https://www.syu.ac.kr/about-sahmyook/regulations-and-cradles/cradle/",
    "https://www.syu.ac.kr/about-sahmyook/regulations-and-cradles/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history-1/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history-2/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history-3/",
    "https://www.syu.ac.kr/about-sahmyook/history-vision/history-4/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/mvp-certificate-2013/mvp-certificate/",
    "https://www.syu.ac.kr/admissions-education/undergraduate-education/mvp-certificate-2013/mvp-certificate-elite/",
    "https://www.syu.ac.kr/school-life/facility-information/cafeteria/",
    "https://www.syu.ac.kr/school-life/facility-information/in-store/",
    "https://www.syu.ac.kr/school-life/facility-information/cafeteria/cafeteria-3/",
    "https://www.syu.ac.kr/school-life/facility-information/optician/",
    "https://www.syu.ac.kr/school-life/facility-information/salon/",
    "https://www.syu.ac.kr/school-life/facility-information/copy-room/",
    "https://www.syu.ac.kr/school-life/facility-information/bookstore/",
    "https://www.syu.ac.kr/school-life/facility-information/our-bank/",
    "https://www.syu.ac.kr/school-life/facility-information/post-office/",
    "https://www.syu.ac.kr/school-life/facility-information/nh/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/welfare-facilities-guide/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/girls-lounge/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/male-student-lounge/",
    "https://www.syu.ac.kr/school-life/circles/founding-club/",
    "https://www.syu.ac.kr/school-life/circles/general-club/",
    "https://www.syu.ac.kr/school-life/circles/employment-club/",
    "https://www.syu.ac.kr/sahmyook/notice/",
    "https://www.syu.ac.kr/school-life/military-information/reserve-forces/",
    "https://www.syu.ac.kr/school-life/venue-rental-info/application/",
    "https://www.syu.ac.kr/school-life/venue-rental-info/voting-guide/",
    "https://www.syu.ac.kr/academic/scholarship-information/",
    "https://www.syu.ac.kr/academic/registration-information/",
    "https://www.syu.ac.kr/academic/registration-information/payment-of-tuition/",
    "https://www.syu.ac.kr/academic/registration-information/installment-payment/",
    "https://www.syu.ac.kr/academic/registration-information/returning-tuition-delinquent/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/total-student-body/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/representative-council/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/academy/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/english-newspaper/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/club-society/",
    "https://www.syu.ac.kr/administrative-support-information/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/sinmungo3/sinmungo_write/",
    "https://www.syu.ac.kr/management-policy-before-20200401/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/campus-tour-application/campus-tour-application-form/",
    "https://www.syu.ac.kr/about-sahmyook/",
    "https://www.syu.ac.kr/%ec%a4%80%eb%b9%84%ec%a4%91-%ed%8e%98%ec%9d%b4%ec%a7%80/",
    "https://www.syu.ac.kr/personal-information-file-status/",
    "https://www.syu.ac.kr/personal-information-third-party-status/",
    "https://www.syu.ac.kr/personal-information-processing-consignment-status/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/campus-tour-application/campus-tour-application-form-print/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/sinmungo3/sinmungo_single/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/sinmungo-form/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/guide-to-welfare-all/",
    "https://www.syu.ac.kr/school-life/facility-information/facility-information-all/",
    "https://www.syu.ac.kr/school-life/student-autonomy-organization/student-autonomy-organization-all/",
    "https://www.syu.ac.kr/academic/scholarship-information/scholarship-benefits-review/scholarship-benefits-review-form/",
    "https://www.syu.ac.kr/etc/login/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/health-promotion-center/",
    "https://www.syu.ac.kr/school-life/guide-to-welfare/disability-student-support-center/",
    "https://www.syu.ac.kr/etc/logout/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/vr-campus-tour/",
    "https://www.syu.ac.kr/school-life/certificate/proof-of-report-card/",
    "https://www.syu.ac.kr/school-life/certificate/student-id/",
    "https://www.syu.ac.kr/administrative-support-information/bachelors-and-administrative-systems/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/chaplain-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/museum-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/academic-affairs-office-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/publish-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/computing-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/disable_support-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/student-affairs-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/prohibit-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/office-of-planning-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/inter_edu-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/health-promotion-center-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/counsel_center/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/affiliated-organization/culture_center-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/business-affairs-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/research-industry-academic-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/admissions-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/well-rounded-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/research-business-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/educational-innovation-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/direct-organization/reserve-forces-jobs-in-charge/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/fund-jobs-in-charge/",
    "https://www.syu.ac.kr/academic/scholarship-information/scholarships/",
    "https://www.syu.ac.kr/academic/scholarship-information/suburban-scholarship-information/",
    "https://www.syu.ac.kr/university-square/notice/",
    "https://www.syu.ac.kr/university-square/syu-news/",
    "https://www.syu.ac.kr/university-square/promotion/",
    "https://www.syu.ac.kr/university-square/gallery/",
    "https://www.syu.ac.kr/university-square/promotion/student-promotion-division/",
    "https://www.syu.ac.kr/university-square/promotion/webzine/",
    "https://www.syu.ac.kr/university-square/promotion/brochure/",
    "https://www.syu.ac.kr/university-square/promotion/advertising-2/",
    "https://www.syu.ac.kr/university-square/gallery/photo/",
    "https://www.syu.ac.kr/university-square/gallery/video/",
    "https://www.syu.ac.kr/university-square/promotion/student-promotion-division/su-ambassador/",
    "https://www.syu.ac.kr/university-square/promotion/student-promotion-division/su-love/",
    "https://www.syu.ac.kr/university-square/gallery/promotional-video/",
    "https://www.syu.ac.kr/university-square/promotion/student-promotion-division/activities-gallery/",
    "https://www.syu.ac.kr/newsletter-signup/",
    "https://www.syu.ac.kr/industry-academic-research/irb-introduction/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/institute-for-mission-and-social-problems/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/theological-institute/",
    "https://www.syu.ac.kr/chronic-disease-research-institute/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/natural-science-institute/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/korea-institute-of-health-evaluation/",
    "https://www.syu.ac.kr/science-institute/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/marine-life-resources-institute/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/biomaterial-research-institute/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/chromosome-research-institute/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/etc-notice/",
    "https://www.syu.ac.kr/%ec%84%a4%eb%ac%b8/",
    "https://www.syu.ac.kr/rev-20160512/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/accreditation/",
    "https://www.syu.ac.kr/admissions-education/college/nursing1/",
    "https://www.syu.ac.kr/admissions-education/college/future-convergence/",
    "https://www.syu.ac.kr/admissions-education/su-mvp/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/uimyung-research-institute-for-neuroscience/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/nanobiomaterials-research-institute/",
    "https://www.syu.ac.kr/biomaterials-research-institute-pending/",
    "https://www.syu.ac.kr/university-square/syu-news/interview/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/presidents-work-promotion-expenses/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/bioavailability-control-lab/",
    "https://www.syu.ac.kr/about-sahmyook/college-guide/campusmap/",
    "https://www.syu.ac.kr/university-square/syu-news/contribution-2/",
    "https://www.syu.ac.kr/about-sahmyook/general-office/greetings/",
    "https://www.syu.ac.kr/about-sahmyook/organization-department/administrative-organizations/financial-affairs-jobs-in-charge/",
    "https://www.syu.ac.kr/eclass-introduction-home/",
    "https://www.syu.ac.kr/sahmyook/corporate-constitution-detail/",
    "https://www.syu.ac.kr/privacy-policy-before-20220227/",
    "https://www.syu.ac.kr/management-policy-before-20240215/",
    "https://www.syu.ac.kr/sahmyook/donation/",
    "https://www.syu.ac.kr/university-square/syu-news/mission-story/",
    "https://www.syu.ac.kr/academic/scholarship-information/government-scholarship/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/convergence-research-center-for-biohealth/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/open-director-recommendation-committee/",
    "https://www.syu.ac.kr/about-sahmyook/public-announcement/fund-management-council/",
    "https://www.syu.ac.kr/privacy-policy-before-20210222/",
    "https://www.syu.ac.kr/personal-information-file-status-before-20210221/",
    "https://www.syu.ac.kr/personal-information-third-party-status-before-20210221/",
    "https://www.syu.ac.kr/personal-information-processing-consignment-status-before-20210221/",
    "https://www.syu.ac.kr/management-policy-before-20210222/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/ai-convergence-research-center/",
    "https://www.syu.ac.kr/university-square/syu-news/teachers-press-activities/",
    "https://www.syu.ac.kr/management-policy-before-20220228/",
    "https://www.syu.ac.kr/etc/privacy-policy/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/padam-natural-material/",
    "https://www.syu.ac.kr/about-sahmyook/phone-number-information/",
    "https://www.syu.ac.kr/about-sahmyook/long-term-planning/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/person-centered-practices/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/su-service-design-lab/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/vr-healthcare-content-lab/",
    "https://www.syu.ac.kr/management-policy-before-20230228/",
    "https://www.syu.ac.kr/about-sahmyook/symbols-ui/character/",
    "https://www.syu.ac.kr/privacy-policy-before-20230228/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/construction-management-and-convergence-technology/",
    "https://www.syu.ac.kr/university-square/notice/public-interest-notice/",
    "https://www.syu.ac.kr/management-policy/",
    "https://www.syu.ac.kr/privacy-policy-before-20240229/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/institute-of-environmental-ecology/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/apl/",
    "https://www.syu.ac.kr/industry-academic-research/a-research-institute/%eb%a9%b4%ec%97%ad%ed%99%9c%ec%84%b1%eb%b0%94%ec%9d%b4%ec%98%a4%ec%9d%98%ec%95%bd%ed%92%88%ea%b0%9c%eb%b0%9c%ec%97%b0%ea%b5%ac%ec%86%8c/"
]

# 결과를 저장할 파일 열기
data = []  # 결과를 저장할 리스트

for url in urls:
    # 각 URL에 대해 HTTP GET 요청을 보냄
    response = requests.get(url)

    # 요청이 성공적인 경우, 즉 HTTP 상태 코드가 200인 경우
    if response.status_code == 200:
        # BeautifulSoup 객체 생성
        soup = BeautifulSoup(response.text, 'html.parser')

        title_tag = soup.find('title')
        if title_tag:
            title = title_tag.text
            # " - 삼육대학교" 부분을 제거
            title = title.rsplit(" – 삼육대학교", 1)[0]
        else:
            title = "Title not found"

        # 결과 리스트에 딕셔너리 형태로 URL과 제목을 추가
        data.append({"URL": url, "Title": title})

    else:
        data.append({"URL": url, "Title": "Failed to retrieve"})

# 결과를 JSON 파일로 저장
with open("output_titles.json", "w", encoding="utf-8") as file:
    json.dump(data, file, ensure_ascii=False, indent=4)